{
 "title": "Kubernetes / Network Observability / Networking",
 "description": "The Grafana dashboard for Network Observability add-on for AKS.\r\n\r\n•\tGet access to cluster level network metrics like packet drops, connections stats and more.  \r\n•\t(Coming soon) Access to pod-level metrics for tracking network errors\r\n",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster Name",
    "query": {
     "query": "label_values(kube_node_info, cluster)"
    }
   },
   {
    "name": "Node",
    "label": "Node",
    "query": {
     "query": "label_values(kube_node_info{cluster=\"$cluster\"}, node)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Network Observability Metrics \n\nUse this dashboard to visualise metrics from the Network Observability add-on for AKS. Dashboard displays metrics from Linux and Windows Clusters. To hide the irrelevant metrics, simply collapse the unwanted sections. Alternatively, you can edit the dashboard to delete unwanted panels. For any questions or issues, please see [our documentation](https://aka.ms/NetObsAddonDoc) "
   }
  },
  { "title": "Traffic stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Egress Bytes ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(kappie_forward_bytes{direction=\"egress\", cluster=~\"$cluster\", instance=~\"$Node\"}[$__rate_interval]))",
     "legendFormat": "Egress Bytes"
    }
   ]
  },
  {
   "title": "Egress Packets",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(kappie_forward_count{direction=\"egress\", cluster=~\"$cluster\", instance=~\"$Node\"}[$__rate_interval]))",
     "legendFormat": "Egress Packets"
    }
   ]
  },
  {
   "title": "Ingress Bytes ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(kappie_forward_bytes{direction=\"ingress\", cluster=~\"$cluster\", instance=~\"$Node\"}[$__rate_interval]))",
     "legendFormat": "Ingress Bytes"
    }
   ]
  },
  {
   "title": "Ingress Packets",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 5 },
   "targets": [
    {
     "expr": "sum(rate(kappie_forward_count{direction=\"ingress\", cluster=~\"$cluster\", instance=~\"$Node\"}[$__rate_interval]))",
     "legendFormat": "Ingress Packets"
    }
   ]
  },
  {
   "title": "Total Bytes by Cluster",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum by(cluster) (rate(kappie_forward_count{cluster=~\"$cluster\", instance=~\"$Node\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Drop stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Packets Dropped - Egress",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(kappie_drop_count{direction=\"egress\", cluster=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Dropped Packets (Egress)"
    }
   ]
  },
  {
   "title": "Packets Dropped - Ingress",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(kappie_drop_count{direction=\"ingress\", cluster=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Dropped Packets (Ingress)"
    }
   ]
  },
  {
   "title": "Packets Dropped - Unknown",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(kappie_drop_count{direction=\"unknown\", instance=~\"$Node\", cluster=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Dropped Packets (Unknown)"
    }
   ]
  },
  {
   "title": "Bytes Dropped by Reason",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(reason) (rate(kappie_drop_bytes{cluster=~\"$cluster\", instance=~\"$Node\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Packets Dropped by Reason",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(reason) (rate(kappie_drop_count{cluster=~\"$cluster\", instance=~\"$Node\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bytes Dropped by Cluster",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(cluster) (rate(kappie_drop_bytes{cluster=~\"$cluster\", instance=~\"$Node\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Packets Dropped by Cluster",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(cluster) (rate(kappie_drop_count{cluster=~\"$cluster\", instance=~\"$Node\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Connection Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "TCP Active Connections by State",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "sum by(state) (kappie_tcp_state{cluster=~\"$cluster\", instance=~\"$Node\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TCP Active Connection count by Remote Addr",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "sum by(address) (kappie_tcp_connection_remote{cluster=~\"$cluster\", instance=~\"$Node\", address!=\"127.0.0.1\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TCP Connection Stats - Timeouts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "sum(rate(kappie_tcp_connection_stats{statistic_name=\"tcptimeouts\", cluster=~\"$cluster\", instance=~\"$Node\"}[$__rate_interval]))",
     "legendFormat": "TCP Timeouts"
    }
   ]
  },
  {
   "title": "TCP Connection Stats - Resets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 44 },
   "targets": [
    {
     "expr": "sum(rate(kappie_tcp_connection_stats{statistic_name=\"resetcount\", cluster=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "TCP Resets"
    }
   ]
  },
  {
   "title": "TCP Connection Stats - Reorder",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 44 },
   "targets": [
    {
     "expr": "sum(rate(kappie_tcp_connection_stats{statistic_name=\"tcptsreorder\", cluster=~\"$cluster\", instance=~\"$Node\"}[$__rate_interval]))",
     "legendFormat": "TCP Reorders"
    }
   ]
  },
  {
   "title": "TCP Flags total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "sum(rate(kappie_tcp_flag_counters[$__rate_interval]))",
     "legendFormat": "Flag Set Packets"
    }
   ]
  },
  {
   "title": "TCP Flags - Resets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 52 },
   "targets": [
    {
     "expr": "sum(rate(kappie_tcp_flag_counters{flag=\"rst\", cluster=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "TCP Reset Packets"
    }
   ]
  },
  {
   "title": "TCP Flags - SYNACK",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 52 },
   "targets": [
    {
     "expr": "sum(rate(kappie_tcp_flag_counters{flag=\"synack\", cluster=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "TCP SYNACK packets "
    }
   ]
  },
  {
   "title": "UDP Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "sum(kappie_udp_connection_stats{statistic_name=\"active\", cluster=~\"$cluster\", instance=~\"$Node\"})",
     "legendFormat": "Total UDP Connections"
    }
   ]
  },
  { "title": "Interface Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "RX Packets by Interface",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 68 },
   "targets": [
    {
     "expr": "sum by(interface_name) (rate(kappie_interface_stats{statistic_name=\"rx_packets\", cluster=~\"$cluster\", instance=~\"$Node\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TX Packets by Interface",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 68 },
   "targets": [
    {
     "expr": "sum by(interface_name) (rate(kappie_interface_stats{statistic_name=\"tx_packets\", cluster=~\"$cluster\", instance=~\"$Node\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rx Cache full error",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 68 },
   "targets": [
    {
     "expr": "sum(rate(kappie_interface_stats{statistic_name=\"rx0_cache_full\", cluster=~\"$cluster\", instance=~\"$Node\"}[$__rate_interval]))",
     "legendFormat": "Rx Cache full errors"
    }
   ]
  },
  {
   "title": "Tx No Op errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 68 },
   "targets": [
    {
     "expr": "kappie_interface_stats{statistic_name=\"tx0_nop\", cluster=~\"$cluster\", instance=~\"$Node\"}",
     "legendFormat": "TX No Op"
    }
   ]
  }
 ]
}